name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    name: test
    timeout-minutes: 15
    runs-on: ubuntu-24.04

    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v6.0.2
        with:
          persist-credentials: false

      - name: validate locks
        run: script/validate-locks --ci

      - name: prepare rust
        run: script/prepare-rust

      - name: install test tools
        run: script/install-test-tools

      - name: bootstrap
        run: script/bootstrap

      - name: test with coverage
        run: script/test --coverage
